### ISSUE TITLE
if the json-schema has cascadingly embedded object,   it will be of some practical significance

### ISSUE THREAD

**Issue by epiphyllum** [mpollmeier/scalameta-tutorial-scaladays#1]

**Comment by mpollmeier** [comment]
?

**Comment by epiphyllum** [comment]
https://github.com/epiphyllum/scalameta-json2case-auto

**Comment by epiphyllum** [comment]
my IntelliJ EAP version:
```
IntelliJ IDEA 2017.1
Build #IU-171.3780.52, built on March 15, 2017
JRE: 1.8.0_112-release-736-b10 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.3￼
```

![image](https://user-images.githubusercontent.com/8348065/27081654-04778e2a-5074-11e7-91b1-2969d96fbc95.png)

![image](https://user-images.githubusercontent.com/8348065/27081665-0bc2f9bc-5074-11e7-8e3b-957811fd9022.png)

**Comment by epiphyllum** [comment]
how to make Intellij happy

**Comment by mpollmeier** [comment]
not sure. you should use the `nightly` scala plugin version though (configure somewhere in plugin properties)
